### ISSUE TITLE
Deserializing json to products crashes because decimals are not nullable in product definition

### ISSUE THREAD

**Issue by DaniusLabs** [XiaoFaye/WooCommerce.NET#21]
if they are nulls in DB

**Comment by XiaoFaye** [comment]
May I ask which version are you using? I recall that this has been fixed in the latest version.

**Comment by DaniusLabs** [comment]
Hi and Thank you for coming back to me. 

This is **Xamarin** project and i got latest package from nuget. 

Updating WooCommerceNET...
No updates available for 'WooCommerceNET' in project 0.5.1
I might have to pull your source files to figure out which property it is. I do see you have them declared as decimal?, but it seems to still fail pulling products. 

InnerException	{System.Xml.XmlException: The value '' cannot be parsed as the type 'decimal'. ---> System.FormatExce…}	System.Xml.XmlException

Thanks again.

**Comment by XiaoFaye** [comment]
I think the property is in one of the sub-item of product, can you let me know which one it is? it should be a quick fix.

**Comment by DaniusLabs** [comment]
I managed to get it to work using newtosoft json. It parsed datetime and string values just fine. 

something like this.
  public T DeserializeJSon<T>(string jsonString)
        {

            return Newtonsoft.Json.JsonConvert.DeserializeObject<T>(jsonString);

        }

looking at your code, i am not sure if empty string value here would not cause parsing error. 

        /// <summary>
        /// Current product price. This is setted from regular_price and sale_price. 
        /// read-only
        /// </summary>
        [DataMember(EmitDefaultValue = false, Name = "price")]
        private object priceValue { get; set; }

        public decimal? price { get; set; }

**Comment by DaniusLabs** [comment]
in my case unit test only went green when I set sale_price and unit_test to "0". 
Would not deserialize otherwise.

in any case thanks for your help and quick response.

**Comment by XiaoFaye** [comment]
I'm having the below code to fix the decimal values return as empty string '' issue, you can see the actual code in JsonObject. But I was not doing this fix for all decimal fields, only some of them that having the issue when I was doing testing.

It's so frustrating because WC REST API returns null decimal in empty string but not 'null' in the json.

It's true that newtosoft json will work fine with it, just not sure if it's worth to import a dependency for such a simple functionality. what do you think?

    /// <summary>
    /// Current product price. This is setted from regular_price and sale_price. 
    /// read-only
    /// </summary>
    [DataMember(EmitDefaultValue = false, Name = "price")]
    private object priceValue { get; set; }

    public decimal? price { get; set; }

**Comment by DaniusLabs** [comment]
I would need to check but i think simply declaring decimal? without [object] property wrapper should do the trick. I always use newtosoft, very lightweight so has not been an issue for me. Also i don't think you need classes like DimensionList. Property of List<Dimension> should suffice. Structure of my customers Product File is somewhat different from class, so i cant really advise what your final code should be. Your work has pointed me in right direction though. Thanks for making it open source and keep the good work. 

Daniel
